name: app
description: Flutter Architecture Blueprints project.
version: 1.0.0+1

publish_to: 'none'

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=2.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # For Google and Firebase
  firebase_core: ^1.1.0
  firebase_crashlytics: ^2.0.0
  firebase_performance: ^0.7.0

  # For Architecture
  flutter_hooks: ^0.16.0
  hooks_riverpod: ^0.14.0

  # For Networking
  dio: ^4.0.0-beta4
  # TODO: dio_firebase_performance does not yet support NNBD.
  # dio_firebase_performance: ^0.3.0
  # For User-Agent Client Hints
  ua_client_hints: ^1.0.3

  # For Model
  json_serializable: ^4.1.0
  freezed_annotation: ^0.14.0

  # For DateTime
  intl: ^0.17.0

  # For Key-Value local storage
  shared_preferences: ^2.0.0

  # Convert between Enum and String
  enum_to_string:

  # For UIs
  gap: ^2.0.0
  cupertino_icons: ^1.0.0
  google_fonts: ^2.0.0
  flutter_svg: ^0.22.0
  sprintf: ^6.0.0-nullsafety
  wakelock: ^0.5.2

  # For geolocation
  geolocator: ^7.0.3
  geocoding: ^2.0.0

  # For Utilities
  get: ^4.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^1.12.0
  flutter_gen_runner: ^3.0.0

  # For Model
  freezed: ^0.14.0

  # For Analyzer
  effective_dart: ^1.3.0

  # For Testing
  mocktail: ^0.1.1
  mocktail_image_network: ^0.1.0

flutter_gen:
  integrations:
    flutter_svg: true

  colors:
    inputs:
      - assets/color/colors.xml
flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/svgs/

  fonts:
    - family: Rotunda
      fonts:
        - asset: assets/fonts/Rotunda-Bold.otf
          weight: 700
