name: app
description: Flutter Architecture Blueprints project.
version: 1.0.0+1

publish_to: 'none'

environment:
  sdk: '>=2.18.6 <3.0.0'
  flutter: '>=3.19.3'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # For Architecture
  flutter_hooks: ^0.18.5+1
  hooks_riverpod: ^2.1.1
  state_notifier: ^0.7.2+1

  # For Networking
  dio: ^4.0.6

  # For Model
  json_serializable: ^6.5.4
  freezed_annotation: ^2.2.0

  # For DateTime
  intl: ^0.18.1

  # For Key-Value local storage
  shared_preferences: ^2.0.12
  path_provider: ^2.0.12

  # Convert between Enum and String
  enum_to_string:

  # For UIs
  gap: ^3.0.1
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  flutter_svg: 2.0.0
  sprintf: ^7.0.0
  wakelock_plus: ^1.2.2

  # For geolocation
  geolocator: ^11.0.0
  geocoding: ^3.0.0

  # For Utilities
  get: ^4.6.6

module:
  androidX: true

dependency_overrides:
  platform: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.3.3
  flutter_gen_runner: ^5.2.0

  # For Model
  freezed: ^2.3.2

  # For Analyzer
  effective_dart: ^1.3.0

flutter_gen:
  enabled: true
  output: lib/gen/
  integrations:
    flutter_svg: true

  colors:
    inputs:
      - assets/color/colors.xml
flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/svgs/

  fonts:
    - family: Rotunda
      fonts:
        - asset: assets/fonts/Rotunda-Bold.otf
          weight: 700
