name: app
description: Flutter Architecture Blueprints project.
version: 1.0.0+1

publish_to: 'none'

environment:
  sdk: '>=2.18.6 <3.0.0'
  flutter: '>=3.3.10'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # For Architecture
  flutter_hooks: ^0.18.5+1
  hooks_riverpod: ^2.1.1

  # For Networking
  dio: ^4.0.6

  # For Model
  json_serializable: ^6.5.4
  freezed_annotation: ^2.2.0

  # For DateTime
  intl: ^0.17.0

  # For Key-Value local storage
  shared_preferences: ^2.0.0

  # Convert between Enum and String
  enum_to_string:

  # For UIs
  gap: ^2.0.0
  cupertino_icons: ^1.0.0
  google_fonts: ^2.0.0
  flutter_svg: ^0.22.0
  sprintf: ^7.0.0
  wakelock: ^0.6.2

  # For geolocation
  geolocator: ^7.0.3
  geocoding: ^2.0.0

  # For Utilities
  get: ^4.1.3

module:
  androidX: true

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.3.3
  flutter_gen_runner: ^5.1.0+1

  # For Model
  freezed: ^2.3.2

  # For Analyzer
  effective_dart: ^1.3.0

flutter_gen:
  integrations:
    flutter_svg: true

  colors:
    inputs:
      - assets/color/colors.xml
flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/svgs/

  fonts:
    - family: Rotunda
      fonts:
        - asset: assets/fonts/Rotunda-Bold.otf
          weight: 700
